# Generated by Django 5.2.6 on 2025-09-13 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='star_rating',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='screenshot_url',
        ),
        migrations.AddField(
            model_name='achievement',
            name='icon',
            field=models.CharField(default='🏆', max_length=10),
        ),
        migrations.AddField(
            model_name='publication',
            name='screenshot_id',
            field=models.CharField(default='', max_length=255, verbose_name='ID скриншота в Telegram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Скрытый профиль'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_id',
            field=models.BigIntegerField(default=0, unique=True, verbose_name='Telegram ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
    ]
