# Generated by Django 5.2.6 on 2025-09-13 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_telegram_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userachievement',
            options={'ordering': ['-awarded_at']},
        ),
        migrations.AddField(
            model_name='achievement',
            name='rating_points',
            field=models.IntegerField(default=5, help_text='Очки рейтинга за получение', verbose_name='Очки рейтинга'),
        ),
        migrations.AddField(
            model_name='profile',
            name='browser_notifications_enabled',
            field=models.BooleanField(default=False, verbose_name='Push-уведомления'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login_streak_check',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='login_streak',
            field=models.IntegerField(default=0, verbose_name='Серия входов'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating_score',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribed_to',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='boosts',
            field=models.ManyToManyField(blank=True, related_name='boosted_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активна'), ('TARGET_HIT', 'Цель достигнута (TP)'), ('STOP_HIT', 'Стоп сработал (SL)')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(default='🏆', max_length=10, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='screenshot_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID скриншота или URL'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EducationalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Можно использовать Markdown для форматирования')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educational_materials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_overviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
