# Generated by Django 5.2.6 on 2025-09-13 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userachievement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp'], 'verbose_name': 'Сообщение чата', 'verbose_name_plural': 'Сообщения чата'},
        ),
        migrations.AlterModelOptions(
            name='educationalmaterial',
            options={'ordering': ['-created_at'], 'verbose_name': 'Обучающий материал', 'verbose_name_plural': 'Обучающие материалы'},
        ),
        migrations.AlterModelOptions(
            name='marketoverview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Обзор рынка', 'verbose_name_plural': 'Обзоры рынка'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-created_at'], 'permissions': [('can_publish', 'Может создавать публикации'), ('can_moderate', 'Может модерировать публикации')], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={'ordering': ['-awarded_at'], 'verbose_name': 'Достижение пользователя', 'verbose_name_plural': 'Достижения пользователей'},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Отредактировано'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AddField(
            model_name='educationalmaterial',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемый'),
        ),
        migrations.AddField(
            model_name='educationalmaterial',
            name='material_type',
            field=models.CharField(choices=[('ARTICLE', 'Статья'), ('VIDEO', 'Видео'), ('GUIDE', 'Руководство'), ('TUTORIAL', 'Урок')], default='ARTICLE', max_length=20, verbose_name='Тип материала'),
        ),
        migrations.AddField(
            model_name='educationalmaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='educationalmaterial',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AddField(
            model_name='marketoverview',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемый'),
        ),
        migrations.AddField(
            model_name='marketoverview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='marketoverview',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOST', 'Буст публикации'), ('ACHIEVEMENT', 'Новое достижение'), ('PUBLICATION', 'Новая публикация'), ('SYSTEM', 'Системное уведомление')], default='SYSTEM', max_length=20, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Уведомление', max_length=100, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='publication',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='educationalmaterial',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educational_materials', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='educationalmaterial',
            name='content',
            field=models.TextField(help_text='Можно использовать Markdown для форматирования', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='educationalmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='educationalmaterial',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='marketoverview',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_overviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='marketoverview',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='marketoverview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='marketoverview',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='marketoverview',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=255, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login_streak_check',
            field=models.DateField(blank=True, null=True, verbose_name='Последняя проверка серии входов'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscribed_to',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='boosts',
            field=models.ManyToManyField(blank=True, related_name='boosted_publications', to=settings.AUTH_USER_MODEL, verbose_name='Бусты'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активна'), ('TARGET_HIT', 'Цель достигнута (TP)'), ('STOP_HIT', 'Стоп сработал (SL)'), ('CANCELED', 'Отменена')], default='ACTIVE', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.achievement', verbose_name='Достижение'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='awarded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_publications', models.PositiveIntegerField(default=0, verbose_name='Всего публикаций')),
                ('successful_predictions', models.PositiveIntegerField(default=0, verbose_name='Успешных прогнозов')),
                ('total_boosts_received', models.PositiveIntegerField(default=0, verbose_name='Получено бустов')),
                ('total_boosts_given', models.PositiveIntegerField(default=0, verbose_name='Дано бустов')),
                ('profile_views', models.PositiveIntegerField(default=0, verbose_name='Просмотры профиля')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статистика пользователя',
                'verbose_name_plural': 'Статистика пользователей',
            },
        ),
    ]
