# Generated by Django 5.2.6 on 2025-09-13 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_achievement_options_alter_chatmessage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRatingAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('points', models.IntegerField(default=0, verbose_name='Очки')),
            ],
            options={
                'verbose_name': 'Дневной агрегат рейтинга',
                'verbose_name_plural': 'Дневные агрегаты рейтинга',
            },
        ),
        migrations.CreateModel(
            name='RatingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(verbose_name='Изменение')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Изменение рейтинга',
                'verbose_name_plural': 'Изменения рейтинга',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('period', models.CharField(help_text='Например: "week", "month", "season"', max_length=50, verbose_name='Период')),
                ('top_n', models.PositiveIntegerField(default=0, verbose_name='Кол-во в топе')),
                ('data_raw', models.TextField(default='[]', verbose_name='Данные (JSON как текст)')),
            ],
            options={
                'verbose_name': 'Снимок рейтинга',
                'verbose_name_plural': 'Снимки рейтинга',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='season_number',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Номер сезона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='login_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Серия входов'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating_score',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='awarded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата получения'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['-created_at'], name='app_publica_created_fc025b_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['-awarded_at'], name='app_userach_awarded_9e569d_idx'),
        ),
        migrations.AddField(
            model_name='dailyratingaggregate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='ratingchange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_changes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='dailyratingaggregate',
            index=models.Index(fields=['date', 'user'], name='app_dailyra_date_e81f00_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyratingaggregate',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='ratingchange',
            index=models.Index(fields=['created_at', 'user'], name='app_ratingc_created_965ab9_idx'),
        ),
    ]
