# Generated by Django 5.2.6 on 2025-09-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_dailyratingaggregate_ratingchange_ratingsnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOST', 'Буст публикации'), ('ACHIEVEMENT', 'Новое достижение'), ('PUBLICATION', 'Новая публикация'), ('SYSTEM', 'Системное уведомление'), ('MARKET_OVERVIEW', 'Новый обзор рынка'), ('FOLLOW', 'Новая подписка')], default='SYSTEM', max_length=20, verbose_name='Тип'),
        ),
    ]
